	subroutine F(t,y,yp)

	YP=-Y/(Y+2)
	
	end


	PROGRAM RKF
	PARAMETER NEQN = 1
	EXTERNAL F
	INTEGER IFLAG,IWORK(5)
	REAL RELERR, ABSERR,WORK(3+6*NEQN),T,TOUT,Y
	RELERR=0.000001
	ABSERR=0.000001
	Y=4
	IFLAG=1
	T=0
	TN=T
	TKON=55
	H=1
	DO TOUT = TN,TKON,H
	CALL RKF45(F,NEQN,Y,T,TOUT,RELERR,ABSERR,IFLAG,WORK,IWORK)
	WRITE (6,*) 'VIXOD=',TOUT,T,'Y=',Y,'FLAG=',IFLAG
	END DO
	END 
